version: '3'

services:
  discord-gif-cop-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - discord-gif-cop-bot-network
    volumes:
      - ./settings.json:/home/node/app/settings.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro

networks:
  discord-gif-cop-bot-network: